// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:life_on_graph/models/heart_rate_record_model.dart';
import 'package:life_on_graph/models/sleep_record_model.dart';
import 'package:life_on_graph/models/steps_record_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HeartRateRecordModelAdapter());
    registerAdapter(SleepRecordModelAdapter());
    registerAdapter(StepsRecordModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(HeartRateRecordModelAdapter());
    registerAdapter(SleepRecordModelAdapter());
    registerAdapter(StepsRecordModelAdapter());
  }
}
